import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={` ${inter.className} center-grid  `}>
				<div className='grid_txt_2'>
					<h1>Hello there!! </h1>
					<p>
						{" "}
						open ur code <b>Terminal</b> and run{" "}
						<b>
							<kbd>npm run email</kbd>
						</b>
					</p>
					<p>
						{" "}
						then navigate to port <b>3030</b> in ur browser url to see your email templates
					</p>

					<h2>
						start building by editing the files within the <kbd>/email</kbd> directory{" "}
					</h2>

					<p>
						{" "}
						you can read this article{" "}
						<Link
							href={
								"https://www.dropbox.com/scl/fi/9jjb0nm9xq7pjow3c4pbl/Creating-and-dispatching-component-based-email-templates-in-Next.js-13-applications.paper?rlkey=tt6qm6qi4lv3z4h9afcq2oeuc&dl=0"
							}
							rel='no-referer'
							target='_blank'
							className='bg-r col-acc-2'
						>
							here
						</Link>{" "}
						if you want a more detailed setup
					</p>

					<h3 className='col-red'>happy hacking!!</h3>
				</div>
			</main>
		</>
	);
}
